### ISSUE TITLE
Add Dataで日付け入力中にカーソルキーで操作

### ISSUE THREAD

**Issue by kexnichi** [ht164/AccountBook#13]
カーソルキーで操作すると、日付け入力欄の前の文字に一づいて欲しいのに、カレンダーが動く

**Comment by ht164** [comment]
日付入力欄をフォーカスするとカレンダーが表示されて、カレンダーにフォーカスが移るのでカーソルキーはカレンダーを動かすようになります。
なので、日付入力欄に直接入力したいのに、カレンダーが表示されてしまうことが問題ですね。

**Comment by ht164** [comment]
テキストボックスをクリックではなく、その横のボタンをクリックして、カレンダーを開くようにした。
そのため、テキストボックスを直接編集することが可能。キーボードでカーソル移動もできる。

9595c0ee6f0cb1e404211b5c5262e26f66ac1308

**Comment by ht164** [comment]
というわけで、クローズします。
